services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8803:8080" # MinIO Console through nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - minio
    restart: always

  minio:
    # image: quay.io/minio/minio
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      - "9000:9000"  # Direct MinIO API access
    expose:  # Only expose to internal network
      - "9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio99}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
      USERS: ${USERS:-}
      PASSWORDS: ${PASSWORDS:-}
      # Optional: Enable audit logging for better monitoring
      MINIO_AUDIT_WEBHOOK_ENABLE: "on"
      MINIO_AUDIT_WEBHOOK_ENDPOINT: "http://nginx:8080/audit"
      MINIO_BROWSER_UPLOAD_LIMIT: 10GiB # Adjust as needed
      # Backup configuration
      BACKUP_DIR_LOCAL: ${BACKUP_DIR_LOCAL:-/mnt/backup/minio}
    command: server /data --console-address ":9001"
    restart: always
    volumes:
      - minio_data:/data
      - ./conf/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

volumes:
  minio_data:
  nginx_logs: